upf4ros2_navigation_action:
  ros__parameters:
    wps:
      - "entrance"
      - "5.80"
      - "-4.63"
      - "-0.77"
      - "0.63"

      - "kitchen"
      - "7.22"
      - "-0.97"
      - "0.002"
      - "1.0"

      - "livingroom"
      - "1.57"
      - "0.70"
      - "-0.001"
      - "1.0"

      - "bedroom"
      - "-6.28"
      - "-0.14"
      - "-0.001"
      - "1.0"

      - "room"
      - "-7.78"
      - "-2.76"
      - "-0.001"
      - "1.0"

      - "gym"
      - "1.85"
      - "4.38"
      - "-0.005"
      - "1.0"

      - "wp1"
      - "1.6916"
      - "-0.05"
      - "0.0"
      - "1.0"

      - "wp2"
      - "2.749"
      - "-0.42"
      - "0.0"
      - "1.0"

      - "wp3"
      - "3.6144"
      - "-1.32"
      - "0.0"
      - "1.0"

      - "base"
      - "0.3"
      - "-0.10"
      - "0.0"
      - "1.0"
